//this file will be automatically generated by python before compiling and executing 
#include <array>

std::array<double, 13 > data { 0.1, 0.2, 0.3, 0.2, 0.8, 0.5, 0.5, 0.4, 0.3, 0.3, 0.3, 0.1, 0.4 };

std::array<size_t, 5 > inputLengths { 3, 2, 2, 3, 3 };
