//this file will be automatically generated by python before compiling and executing 
#include <vector>
#include <array>

//size_t{10}
//constexpr makes this const for arrays.. for some reason
std::array<double,size_t{10}> data {
    0.1, 0.2, 0.3,
    0.2, 0.8,
    0.5, 0.5,
    0.4, 0.1, 0.4
    };

//constexpr
std::array<size_t,4> inputLengths {3,2,2,3};
